// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnO7whYifc-ycmkskezP0G4Sn9akm8dU0',
    appId: '1:941117997109:web:c2c1e242b6a9bd06ecf17c',
    messagingSenderId: '941117997109',
    projectId: 'univhex-50601',
    authDomain: 'univhex-50601.firebaseapp.com',
    storageBucket: 'univhex-50601.appspot.com',
    measurementId: 'G-SP82FRZHVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB18tDVRnI2T6Zmilw4lqClzK9Tm4rYt7M',
    appId: '1:941117997109:android:af799f3fe56a2541ecf17c',
    messagingSenderId: '941117997109',
    projectId: 'univhex-50601',
    storageBucket: 'univhex-50601.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo-BVp-bymOWL1hOMtrjC4bArBq8OFXxU',
    appId: '1:941117997109:ios:7127d30f5488d90aecf17c',
    messagingSenderId: '941117997109',
    projectId: 'univhex-50601',
    storageBucket: 'univhex-50601.appspot.com',
    iosBundleId: 'com.example.univhex',
  );
}
